AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - Rakefile
    - config.ru
    - db/schema.rb
    - bin/*
require:
  - rubocop-minitest
  - rubocop-performance
Metrics/ClassLength:
  Max: 1500
# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - test/**/*
Style/CommentAnnotation:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb
Style/ClassVars:
  Exclude:
    - lib/sens_sms/client.rb
# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true
Style/AsciiComments:
  Enabled: false
# Freeze is so earlier thing
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 120
# Fix Rainbow Gem
# https://github.com/rubocop-hq/rubocop/issues/6398#issuecomment-431901995
inherit_mode:
  merge:
    - Exclude
