name: Test
on:
  push:
jobs:
  Rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.4.x, 2.5.x, 2.6.x, 2.7.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundler Install
        run: bundle install --jobs 4 --retry 3
      - name: Run RuboCop
        run: bundle exec rubocop
  Fasterer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.4.x, 2.5.x, 2.6.x, 2.7.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundler Install
        run: bundle install --jobs 4 --retry 3
      - name: Run Fasterer
        run: bundle exec fasterer
  Minitest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.4.x, 2.5.x, 2.6.x, 2.7.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundler Install
        run: bundle install --jobs 4 --retry 3
      - name: Run Minitest
        run: ruby -Ilib:test test/sens_sms_test.rb
