name: Test
on:
  push:
jobs:
  CacheBundler:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.4.x, 2.5.x, 2.6.x, 2.7.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Cache Bundler
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Bundle install
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
  Rubocop:
    runs-on: ubuntu-latest
    needs: cache_bundler
    strategy:
      matrix:
        ruby: [2.4.x, 2.5.x, 2.6.x, 2.7.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Cache Bundler
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Bundler Install
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run RuboCop
        run: bundle exec rubocop
  Fasterer:
    runs-on: ubuntu-latest
    needs: cache_bundler
    strategy:
      matrix:
        ruby: [2.4.x, 2.5.x, 2.6.x, 2.7.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Cache Bundler
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Bundler Install
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run RuboCop
        run: bundle exec fasterer
  Minitest:
    runs-on: ubuntu-latest
    needs: cache_bundler
    strategy:
      matrix:
        ruby: [2.4.x, 2.5.x, 2.6.x, 2.7.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Cache Bundler
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Bundler Install
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run Minitest
        run: ruby -Ilib:test test/sens_sms_test.rb
